platform :ios, '12.0'

target 'ParalayoutDemo' do
  use_frameworks!

  pod 'Paralayout', :path => '../Paralayout.podspec', :testspecs => ['Tests']

  target 'ParalayoutSnapshotTests' do
  	pod 'SnapshotTesting', '~> 1.8'
  end
end
