target 'ParalayoutDemo' do
  platform :ios, '12.0'
  use_frameworks!

  pod 'Paralayout', :path => '../Paralayout.podspec', :testspecs => ['Tests']

  target 'ParalayoutSnapshotTests' do
  	pod 'SnapshotTesting', '~> 1.8'
  end
end

target 'ParalayoutTVDemo' do
  platform :tvos, '17.0'
  use_frameworks!

  pod 'Paralayout', :path => '../Paralayout.podspec', :testspecs => ['Tests']
end
